# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import trades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('my_id', models.CharField(default=trades.models.create_id, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('sell_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='trades.TypeMoney'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='trades.TypeMoney'),
        ),
    ]
