# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typemoney',
            name='id',
        ),
        migrations.AlterField(
            model_name='typemoney',
            name='name',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
